#基本信息
Port: 8080
#mysql配置
MysqlOpenW: root:root@tcp(localhost:3306)/test
MysqlOpenR: root:root@tcp(localhost:3306)/test
#redis配置
RedisOpenType: Cluster
RedisOpen: localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379,localhost:6379
#session的redis配置
SessionRedisAddress: localhost:6379
SessionRedisPassword:
SessionEncryptionKey: test
SessionName: mysession